title: 'Web applications, mobile web, mobile applications - Konrad Jurkowski'
email: 'konrad@jurkowski.me'
description: >
  Meta description
baseurl: ''
url: 'http://konradjurkowski.pl'
github_username: 'msx2'
twitter_username: 'konradjurkowski'
facebook_username: 'konradjurkowski'
linkedin_url: 'https://pl.linkedin.com/pub/konrad-jurkowski/87/13/aa1'

gems:
  - bootstrap-sass
  - jekyll-slim

sass:
  style: :compressed

slim:
  pretty: true
  format: html5
