title: 'Web applications, mobile web, mobile applications - Konrad Jurkowski'
description: 'Meta description'
baseurl: ''
url: 'http://msx2.github.io'

email: 'konrad@jurkowski.me'
github: 'msx2'
twitter: 'konradjurkowski'
facebook: 'konradjurkowski'
linkedin: 'konradjurkowski'

sass:
  sass_dir: _sass
  style: :compressed

slim:
  pretty: true
  format: html5
