title: Web applications, mobile web, mobile applications - Konrad Jurkowski
email: konrad@jurkowski.me
description: >
  Meta description
baseurl: ''
url: 'http://konradjurkowski.pl'
twitter_username: konradjurkowski
github_username: msx2

slim:
  pretty: true
  format: html5
