title: 'Web applications, mobile web, mobile applications - Konrad Jurkowski'
description: 'Hello! My name is Konrad Jurkowski and I am Full-Stack Ruby on Rails Developer creating responsive and rich Web Applications.'
keywords: 'freelance, freelance developer, full-stack developer, full-stack rails developer, full-stack ruby on rails developer, front-end developer, ruby on rails developer, responsive web design, rwd, web applications, konrad jurkowski, scrum master'

baseurl: ''
url: 'http://msx2.github.io'

email: 'konrad@jurkowski.me'
github: 'msx2'
twitter: 'konradjurkowski'
facebook: 'konradjurkowski'
linkedin: 'konradjurkowski'

sass:
  sass_dir: _sass
  style: :compressed
